routes/admin.php
<?php
use Illuminate\Support\Facades\Route;
///// Route Admin
Route::namespace("App\Http\Controllers\Admin\Auth")->group(function () {
    Route::get('login', 'LoginController@loginForm')->name('admin.login.form');
    Route::post('login', 'LoginController@login')->name('admin.login');
});
Route::namespace("App\Http\Controllers\Admin")->group(function () {
    Route::get('logout', 'Auth\LoginController@logout')->name('admin.logout');
    Route::get('dashboard', "AdminController@dashboard")->name('admin.dashboard');

    Route::get('setting', "SettingController@form")->name('admin.setting');
    Route::post('setting/monetary-unit', "SettingController@monetary_unit")->name('admin.setting.monetary-unit');
    Route::post('setting/trade-swap-status', "SettingController@trade_swap_status")->name('admin.setting.trade-swap-status');
    Route::post('setting/admin-notifs-status','SettingController@admin_notifs_status')->name('admin.setting.notifs-status');

    Route::get('wd-currency-setting','CurrencyController@form')->name('admin.wd-currency-setting');
    Route::post('wd-currency-status','CurrencyController@wd_currency_status')->name('admin.wd-currency-status');
//    Route::get('manage-withdraw-swap-page', 'AdminController@manage_withdraw_swap_page')->name('manage-withdraw-swap-page');
//    Route::post('manage_withdraw_update', 'AdminController@manage_withdraw_update')->name('manage-withdraw-update');
//    Route::post('manage-swap-currency', 'AdminController@manage_swap_update')->name('manage-swap-update');
    Route::post('change-unit', 'AdminController@change_unit')->name('change-unit');
    Route::post('change-unit-for-withdraw', 'AdminController@change_unit_for_withdraw')->name('change-unit-for-withdraw');

    Route::post('withdraw-rial/reject/{id}', 'WithdrawRialController@reject')->name('admin.withdraw-rial.reject');
    Route::post('withdraw-rial/confirm/{id}', 'WithdrawRialController@confirm')->name('admin.withdraw-rial.confirm');
    Route::resource('withdraw-rial', 'WithdrawRialController', ['as' => 'admin']);


    // مدیریت کارمزد ها
    Route::get('manage/fees', "AdminController@fees_index")->name('admin.manage.fees.index');
    Route::post('manage/fees', "AdminController@fees_store")->name('admin.manage.fees.store');


    //    TRADE MANAGE
//    Route::get('trade-management', 'AdminController@manage_trade_page')->name('trade-management');
//    Route::post('trade-fee-update', 'AdminController@trad_fee_update')->name('trad-fee-update');
//    Route::post('trade-fees-update', 'AdminController@trad_fees_update')->name('trad-fees-update'); // اینو خانم سواری گفت post کنم
    Route::get('get-currency-fees', 'AdminController@get_currency_fees')->name('get-currency-fees');
    Route::get('set-fees', 'AdminController@set_fees')->name('set-fees');

    Route::get('users', 'UserController@index')->name('user.index');
    Route::get('users/authenticate/{user}', 'UserController@form_authenticate')->name('user.authenticate.form');
    Route::get('users/authenticate', 'UserController@authenticate')->name('user.authenticate.index');
    Route::get('users/{user}', 'UserController@show')->name('user.show');
    Route::post('users/{user}/wallet', 'UserController@wallet')->name('admin.users.wallet');
    Route::post('users/{user}/reject-dirham-diposit', 'UserController@rejectDirhamDeposit')->name('admin.users.reject_dirham_diposit');
    Route::post('users/{user}/confirm-dirham-diposit', 'UserController@confirmDirhamDeposit')->name('admin.users.confirm_dirham_diposit');
    Route::get('user/changeStatus', 'UserController@change_status');
    Route::post('user/{user}/edit', 'UserController@edit')->name('admin.user.edit');
//    Route::post('user/{user}/role', 'UserController@role')->name('admin.user.manage-role');
    Route::get('user/{user}/login-panel', 'UserController@login_panel')->name('admin.user.login-panel');
    Route::get('user/disableStatus', 'UserController@disable_status');
    Route::get('tickets', 'TicketController@index')->name('ticket.admin.index');
    Route::get('ticket/create', 'TicketController@create')->name('ticket.admin.create');
    Route::post('ticket/store', 'TicketController@store')->name('ticket.admin.store');
    Route::get('my_tickets', 'TicketController@index')->name('my_ticket.admin.index');
    Route::get('ticket/{id}', 'TicketController@show')->name('ticket.admin.show');
    Route::get('ticket/ban/{id}', 'TicketController@ban')->name('ticket.admin.ban');
    Route::get('get-users', 'TicketController@users')->name('admin.users');
    Route::delete('ticket/destroy/{id}', 'TicketController@destroy')->name('ticket.destroy');
    Route::post('ticket/route/{id}', 'TicketController@route')->name('ticket.route');
    Route::post('comment/{id}', 'TicketController@comment')->name('comment.admin.store');
    Route::resource('currencies', 'CurrencyController');
    Route::get('roles', "RolesController@index")->name('roles.index');
    Route::get('roles/create', "RolesController@create")->name('roles.create');
    Route::post('roles/store', "RolesController@store")->name('roles.store');
    Route::get('roles/{id}/edit', "RolesController@edit")->name('roles.edit');
    Route::post('roles/{id}/update', "RolesController@update")->name('roles.update');
    Route::delete('roles/delete', "RolesController@destroy")->name('roles.destroy');
    Route::get('banks', 'BankController@index')->name('admin.bank.index');
    Route::post('banks/{bank}/confirm', 'BankController@confirm')->name('admin.bank.confirm');
    Route::post('banks/{bank}/reject', 'BankController@reject')->name('admin.bank.reject');
    Route::resource('notifications', 'NotificationController');
    Route::get('get-user', 'NotificationController@users')->name('notifications.get_user');
    Route::get('reports', 'ReportController@index')->name('admin.report.index');
    Route::resource('posts', 'PostController');
    Route::post('posts/reject', 'PostController@reject')->name('posts.reject');
    Route::post('posts/accept', 'PostController@accept')->name('posts.accept');
    Route::resource('categories', 'CategoryController');
    Route::post('categories/delete', 'CategoryController@delete')->name('categories.delete');
//    Route::post('manage-fee-withdraw-admin-update', 'AdminController@fee_withdraw_admin_update')->name('manage-fee-withdraw-admin-update');
    Route::get('request/withdraw', 'WDController@index_withdraw')->name('admin.request.withdraw');
    Route::get('request/withdraw/{id}/show', 'WDController@show_withdraw')->name('admin.request.withdraw.show');
    Route::post('request/withdraw/balance/admin', 'WDController@balance_admin')->name('admin.request.withdraw.balance-admin');
    Route::post('request/withdraw/update-status', 'WDController@update_status')->name('admin.request.withdraw.update-status');

    Route::resource('announcements','AnnouncementController')->names('admin.ann');
});

routes/web.php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('logout', function () {
    \Illuminate\Support\Facades\Auth::logout();
    (new Authenticator(request()))->logout();
    return redirect()->route('login.form');
})->name('logout');
Route::get('/image/{type}/{id}/{file}',
    function ($type, $id, $file) {
        $path = storage_path('app/uploaded/' . $type . '/' . $id . '/' . $file);
        if (!File::exists($path)) {
            abort(404);
        }
        $file = File::get($path);
        $type = File::mimeType($path);

        $response = Response::make($file, 200);
        $response->header("Content-Type", $type);
        return $response;
    })->name('image.view');

Route::get('/image/download/{type}/{id}/{file}',
    function ($type, $id, $file) {
        $path = storage_path('app/uploaded/' . $type . '/' . $id . '/' . $file);
        if (!File::exists($path)) {
            abort(404);
        }
        $type = File::mimeType($path);
        $file_name=str_replace('/','.',$type);
        $headers = [
            'Content-Type'        => 'application/octet-stream',
            'Content-Disposition' => 'attachment; filename='. $file_name. ';'
        ];

        return response()->download($path,$file_name,$headers);
    })->name('image.download');
Route::get('get-cities', function () {
    $cities = \App\Models\City::select(['id', 'name'])->where('parent', request('id'))->get();
    $html = '<option value="">انتخاب کنید...</option>';
    foreach ($cities as $row) {
        $html .= '<option value="' . $row->id . '">' . $row->name . '</option>';
    }
    return json_encode($html);
})->name('get-cities');
Route::namespace("App\Http\Controllers\Auth")->middleware('guest')->group(function () {
    Route::get('auth/login', 'LoginRegisterController@loginForm')->name('login.form');
    Route::post('auth/login/verify', 'LoginRegisterController@login')->name('login.login');
    Route::get('auth/register', 'LoginRegisterController@register')->name('register.form');
    Route::post('auth/register/store', 'LoginRegisterController@registerStore')->name('register.store');
    Route::get('forget-password', 'LoginRegisterController@forgetPasswordForm')->name('login.forget_password.form');
    Route::post('forget-password', 'LoginRegisterController@forgetPasswordSendEmail')->name('login.forget_password.send');
    Route::post('forget-change-password', 'LoginRegisterController@forgetChangePassword')->name('login.forget_password.change-password');
    Route::get('/login', 'GoogleController@loginWithGoogle')->name('login');
    Route::get('callback', 'GoogleController@callbackFromGoogle')->name('callback');
});
// SIGN IN WITH GOOGLE ROUTES
//Route::prefix('google')->name('google.')->group( function(){
//    Route::get('/login', ['GoogleController@loginWithGoogle'])->name('login');
//    Route::get('/callback', ['GoogleController@callbackFromGoogle'])->name('callback');
//});
// END
Route::get('verify-email/token/{token}', "App\Http\Controllers\User\StepsController@verifyEmail")->name('step.verify-token.email');
/// Route Landing
Route::namespace("App\Http\Controllers\Landing")->group(function () {
    Route::get('/', 'HomeController@index')->name('landing.home');
    Route::get('/join', 'HomeController@test');
    Route::get('/about-rootix', 'HomeController@about')->name('landing.about');
    Route::get('/blog-page', 'HomeController@blog')->name('landing.blog');
    Route::get('/services', 'HomeController@services')->name('landing.services');
    Route::get('/faq', 'HomeController@faq')->name('landing.faq');
    Route::get('/education', 'HomeController@education')->name('landing.education');
    Route::get('/prices', 'HomeController@prices')->name('landing.prices');
    Route::get('/price-detail/{currency}', 'HomeController@price_detail')->name('landing.price_detail');
    Route::get('/chart', 'HomeController@chart')->name('landing.chart');
    Route::get('/post/{slug}', 'HomeController@post_show')->name('landing.post');
    Route::get('/search', 'HomeController@post_search')->name('landing.search');
    Route::get('/contact-rootix', 'HomeController@contact_us')->name('landing.contact_us');

});

Route::get('withdraw/token/{token}', "App\Http\Controllers\User\WithdrawController@verifyEmail")->name('verify-withdraw.email');
Route::get('reject/token/{token}', "App\Http\Controllers\User\WithdrawController@rejectEmail")->name('reject-withdraw.email');


///// Route User
Route::middleware(['auth', 'steps', '2fa'])->namespace("App\Http\Controllers\User")->group(function () {
    ///// Route Step
    Route::prefix('step')->group(function () {
        Route::get('verify-mobile', "StepsController@mobile")->name('step.verify-mobile');
        Route::get('verify-email', "StepsController@email")->name('step.verify-email');
        Route::post('verify-mobile/send-verify', "StepsController@sendVerify")->name('step.send-verify');
        Route::post('verify-email/send-link', "StepsController@sendEmail")->name('step.send-email');
        Route::get('information', "StepsController@information")->name('step.information');
        Route::post('information/store', "StepsController@informationStore")->name('step.information.store');
        Route::get('bank', "StepsController@bank")->name('step.bank');
        Route::post('bank/store', "StepsController@bankStore")->name('step.bank.store');
        Route::get('upload_document', "StepsController@docs")->name('step.upload');
        Route::post('upload_document/store', "StepsController@DocsStore")->name('step.upload.store');
        Route::get('finish', "StepsController@finish")->name('step.finish');
    });

    Route::post('google2fa/authenticate', function () {
        return redirect(\route('user.dashboard'));
    });
    Route::get('dashboard', "HomeController@dashboard")->name('user.dashboard');
    Route::post('timer_deposit', "HomeController@timer_deposit")->name('user.timer_deposit');
    Route::get('profile', "ProfileController@formProfile")->name('user.profile.form');
    Route::post('profile/about/{id}', "ProfileController@update")->name('profile.update.about');
//    Route::get('swap/{unit}', 'SwapController@show')->name('swap.show');


    Route::get('swap', 'SwapController@index')->name('swap.index');
    Route::post('swap', 'SwapController@store')->name('swap.store');


    Route::post('get-list-currencies', 'AssetController@list_currencies')->name('asset.get_list_currencies');
//    Route::post('get-unit-price', 'SwapController@get_unit_price')->name('get-unit-price');
//    Route::post('get-unit-swap-fee-price', 'SwapController@get_unit_swap_fee_price')->name('get-unit-swap-fee-price');
    Route::post('get_theter_price', 'HomeController@get_theter_price')->name('get_theter_price');
//    Route::post('exchange', 'SwapController@exchange')->name('exchange');
    Route::post('createAccount/{unit}', 'ProfileController@wallet')->name('createAccount');
//    Route::post('check-withdraw-amount', 'WithdrawController@check_withdraw_amount')->name('check-withdraw-amount');
//    Route::post('withdraw-from-wallet', 'WithdrawController@withdraw_from_wallet')->name('withdraw-from-wallet');
//    Route::post('send-message-admin', 'WithdrawController@send_message_admin')->name('send-message-admin');
    Route::post('get-total-usdt', 'WithdrawController@get_total_usdt')->name('get-total-usdt');
//    Route::get('withdraw/{unit}','WithdrawController@index')->name('withdraw.index');
//    Route::post('withdraw','WithdrawController@store')->name('withdraw.store');
    Route::get('withdraw/token/{token}', "WithdrawController@verifyEmail")->name('verify-withdraw.email');

//    Route::resource('withdraw-rial','WithdrawRialController');
    Route::get('wallet/deposit/dirham', 'WDController@dirhamDepositIndex')->name('wallet.deposit.dirham.index');
    Route::get('wallet/withdraw/rial', 'WDController@W_withdraw_index_rial')->name('wallet.withdraw.rial.index');
    Route::get('wallet/withdraw/rial/create', 'WDController@W_withdraw_create_rial')->name('wallet.withdraw.rial.create');
    Route::post('wallet/withdraw/rial', 'WDController@W_withdraw_store_rial')->name('wallet.withdraw.rial.store');

//    Route::get('wallet/deposit/rial/create', 'WDController@W_deposit_create_rial')->name('wallet.deposit.rial.create');
//    Route::post('wallet/deposit/rial', 'WDController@W_deposit_store_rial')->name('wallet.deposit.rial.store');
    Route::get('wallet/deposit/aed/create', 'WDController@W_deposit_create_aed')->name('wallet.deposit.aed.create');
    Route::post('wallet/deposit/aed', 'WDController@W_deposit_store_aed')->name('wallet.deposit.aed.store');

    Route::get('reject/token/{token}', "WithdrawController@rejectEmail")->name('reject-withdraw.email');
    Route::get('change-pass', 'ProfileController@change_pass_view')->name('change_pass.index');
    Route::post('change-pass', 'ProfileController@change_pass')->name('change_pass.store');
    Route::get('/charge-wallet', '\App\Http\Controllers\General\PaymentController@chargeWallet')->name('charge_wallet.view');
    Route::resource('tickets', 'TicketController');
    Route::post('comment/{id}', 'TicketController@comment')->name('comment.store');
    Route::post('/setting/change_confirmation_type', 'SettingController@change_confirmation_type')->name('setting.change_confirmation_type');
    Route::post('/setting/verify_confirmation_type', 'SettingController@verify_confirmation_type')->name('setting.verify_confirmation_type');
    Route::get('setting', 'SettingController@form')->name('setting.form');

app/Models/UserGuard.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class UserGuard extends Model
{
    use HasFactory, SoftDeletes;
    protected $fillable = ["guardable_id", "guardable_type"];

    public function guardable()
    {
        return $this->morphTo(__FUNCTION__, 'guardable_type', 'guardable_id');
    }

    public function getFullnameAttribute()
    {
        $user = $this->user;
        if ($user)
            return $user->first_name . ' ' . $user->last_name;
    }

    public function user()
    {
        return $this->hasOne($this->guardable_type, 'id', 'guardable_id');
    }

    public function getPanelTypeAttribute()
    {
        switch ($this->guardable_type) {
            case "Modules\Admin\Entities\Admin":
                return "ادمین";
                break;
            case "Modules\User\Entities\User":
                return "مشتری";
                break;
        }
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

resources/views/user/ticket/create.blade.php
@extends('templates.user.master_page')
@section('title_browser')
    New Ticket-Rootix Exchange
@endsection
@section('content_class','bank-content')

@section('content')
    <section class="wallet-cart pt-2">
        <div class="container">
            <div class="bank-header">
                <h1 class="dashboard-title bank-title desktop-title">
                    New Ticket
                </h1>
            </div>
        </div>
    </section>

    <form id="ticket-form" action="{{route('tickets.store')}}" method="post" enctype="multipart/form-data">
        @csrf
        <section class="pt-1">
            <div class="container">
                <div class="panel-box h-auto">
                    <div class="row">
                        <div class="col-12 col-md-6 col-lg-4">
                            <div dir="ltr" class="request-box request-box-2 auth__btn request-js-box-2
                          enabled d-flex justify-between items-center">
                                <span class="request-box__title">Title</span>
                                <input type="text" dir="ltr" class="currency-value-input ml-4"
                                       id="currency-value-input-1" name="title"
                                       placeholder="Write the title"/>
                            </div>
                        </div>

                        <div class="col-12 col-md-6 col-lg-4">
                            <div dir="ltr" class="request-box request-box-2 auth__btn request-js-box-2
                          enabled d-flex justify-between items-center">
                                <span class="request-box__title">Department</span>
                                <select class="border-0" name="role_id">
                                    <option value="1">Support</option>
                                    <option value="2">Technical</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-12 col-lg-4">
                            <div dir="ltr" class="request-box request-box-2 auth__btn request-js-box-2 enabled
                          d-flex justify-between items-center">
                                <span class="request-box__title">Urgency</span>
                                <select class="border-0" name="priority">
                                    <option value="1">Low</option>
                                    <option value="2"> Medium</option>
                                    <option value="3"> High</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-12">
                            <div>
                        <textarea name="description"
                                  class="w-100 request-box request-box-2 auth__btn request-js-box-2 enabled
                            border-0 outline-0 ticket__message-box"
                                  placeholder="Write your message"
                        ></textarea>
                            </div>
                        </div>
                    </div>

                    <div class="d-flex align-items-center justify-center mt-4">
                        <div class="photo__name"></div>

                        <label for="upload-btn" class="ticket__btns d-flex">
                            <div class="ticket-upload__btn d-flex align-items-center">
                                <div>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="24"
                                         viewBox="0 0 26.992 30.849">
                                        <path id="Icon_metro-attachment" data-name="Icon metro-attachment"
                                              d="M22.629,11.781,20.673,9.825l-9.785,9.783a4.151,4.151,0,0,0,5.871,5.87L28.5,13.737a6.918,6.918,0,0,0-9.784-9.783L6.388,16.282l-.026.025A9.649,9.649,0,0,0,20.008,29.951l.025-.026h0l8.415-8.414-1.958-1.956-8.415,8.413-.025.025a6.881,6.881,0,0,1-9.733-9.73l.027-.025v0L20.673,5.911a4.151,4.151,0,0,1,5.871,5.87L14.8,23.521a1.383,1.383,0,0,1-1.957-1.956l9.785-9.784Z"
                                              transform="translate(-3.535 -1.928)"/>
                                    </svg>
                                </div>

                                <input name="file" type="file" class="ticket-upload__input d-none" id="upload-btn"
                                       accept="image/*">

                                <span>
                                File
                            </span>
                            </div>
                            <button id="" type="button" class="create-new-bank withdraw-btn ajaxStore">
                                Submit
                            </button>
                        </label>
                    </div>
                </div>
            </div>
        </section>
    </form>
@endsection
@section('script')
    <script src="{{asset('theme/user/scripts/ticket-2.js')}}"></script>
@endsection

resources/views/user/ticket/index.blade.php
@extends('templates.user.master_page')
@section('title_browser')
    Tickets-Rootix Exchange
@endsection
@section('content_class','bank-content')

@section('content')
    <section class="wallet-cart pt-2">
        <div class="container">
            <div class="bank-header">
                <h1 class="dashboard-title bank-title desktop-title">Tickets</h1>
                @can('ticket_create')
                    <a href="{{route('tickets.create')}}" class="create-new-bank">
                        <svg
                            xmlns="http://www.w3.org/2000/svg"
                            width="18.111"
                            height="18.111"
                            viewBox="0 0 18.111 18.111">
                            <g
                                id="Icon_feather-plus"
                                data-name="Icon feather-plus"
                                transform="translate(-6.5 -6.5)">
                                <path
                                    id="Path_8591"
                                    data-name="Path 8591"
                                    d="M18,7.5V23.611"
                                    transform="translate(-2.444)"
                                    fill="none"
                                    stroke="#fff"
                                    stroke-linecap="round"
                                    stroke-linejoin="round"
                                    stroke-width="2"/>
                                <path
                                    id="Path_8592"
                                    data-name="Path 8592"
                                    d="M7.5,18H23.611"
                                    transform="translate(0 -2.444)"
                                    fill="none"
                                    stroke="#fff"
                                    stroke-linecap="round"
                                    stroke-linejoin="round"
                                    stroke-width="2"/>
                            </g>
                        </svg>
                        New ticket
                    </a>
                @endcan
            </div>

            <div>
                <div class="dashboard-table">
                    <div class="row">
                        <div class="col-12">
                            <div class="overflow-auto">
                                <div class="wallet-table-container">
                                    <table class="wallet-table bank-table ticket__table">
                                        <thead>
                                        <tr>
                                            <th>
                                                <div>
                                                    ID
                                                </div>
                                            </th>
                                            <th>
                                                <div>
                                                    Title
                                                </div>
                                            </th>
                                            <th>
                                                <div>
                                                    Department
                                                </div>
                                            </th>
                                            <th>
                                                <div>
                                                    Status
                                                </div>
                                            </th>

                                            <th>
                                                <div>
                                                    Date
                                                </div>
                                            </th>

                                            <th>
                                            </th>
                                        </tr>
                                        </thead>

                                        <tbody>
                                        @if(count($tickets)>0)
                                            @foreach($tickets as $ticket)
                                                @php
                                                    switch ($ticket->status){
                                                        case 1 :
                                                        case 3:
                                                            $status=['status'=>'Pending','class'=>'minus'];
                                                            break;
                                                        case 2:
                                                            $status=['status'=>'Answered','class'=>'plus'];
                                                            break;
                                                        case 4:
                                                            $status=['status'=>'Closed','class'=>'plus'];
                                                            break;
                                                    }
                                                @endphp
                                                <tr>
                                                    <td>
                                                        <div class="text-left">
                                                            {{$ticket->ticket_code}}
                                                        </div>
                                                    </td>

                                                    <td>{!! \Illuminate\Support\Str::limit($ticket->title,20) !!}</td>

                                                    <td>{{$ticket->role_id==1?'Support':'Technical'}}</td>

                                                    <td>

                                    <span class="{{$status['class']}}">
                                        {{$status['status']}}
                                    </span>
                                                    </td>

                                                    <td>{{date_format($ticket->created_at,'d F Y')}}</td>

                                                    <td dir="ltr">
                                                        @can('ticket_show')
                                                            <a href="{{route('tickets.show',$ticket->id)}}"
                                                               class="create-new-bank withdraw-btn">
                                                                View
                                                            </a>
                                                        @endcan
                                                    </td>
                                                </tr>
                                            @endforeach
                                        @else
                                            <tr>
                                                <td colspan="6">There is no ticket to
                                                    show
                                                </td>
                                            </tr>
                                        @endif
                                        </tbody>
                                    </table>
                                    @if(count($tickets)>0)
                                        <div class="pagination__container">
                                            {!! $tickets->links() !!}
                                        </div>
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection
@section('script')

@endsection