routes/admin.php
<?php
use Illuminate\Support\Facades\Route;
///// Route Admin
Route::namespace("App\Http\Controllers\Admin\Auth")->group(function () {
    Route::get('login', 'LoginController@loginForm')->name('admin.login.form');
    Route::post('login', 'LoginController@login')->name('admin.login');
});
Route::namespace("App\Http\Controllers\Admin")->group(function () {
    Route::get('logout', 'Auth\LoginController@logout')->name('admin.logout');
    Route::get('dashboard', "AdminController@dashboard")->name('admin.dashboard');

    Route::get('setting', "SettingController@form")->name('admin.setting');
    Route::post('setting/monetary-unit', "SettingController@monetary_unit")->name('admin.setting.monetary-unit');
    Route::post('setting/trade-swap-status', "SettingController@trade_swap_status")->name('admin.setting.trade-swap-status');
    Route::post('setting/admin-notifs-status','SettingController@admin_notifs_status')->name('admin.setting.notifs-status');

    Route::get('wd-currency-setting','CurrencyController@form')->name('admin.wd-currency-setting');
    Route::post('wd-currency-status','CurrencyController@wd_currency_status')->name('admin.wd-currency-status');
//    Route::get('manage-withdraw-swap-page', 'AdminController@manage_withdraw_swap_page')->name('manage-withdraw-swap-page');
//    Route::post('manage_withdraw_update', 'AdminController@manage_withdraw_update')->name('manage-withdraw-update');
//    Route::post('manage-swap-currency', 'AdminController@manage_swap_update')->name('manage-swap-update');
    Route::post('change-unit', 'AdminController@change_unit')->name('change-unit');
    Route::post('change-unit-for-withdraw', 'AdminController@change_unit_for_withdraw')->name('change-unit-for-withdraw');

    Route::post('withdraw-rial/reject/{id}', 'WithdrawRialController@reject')->name('admin.withdraw-rial.reject');
    Route::post('withdraw-rial/confirm/{id}', 'WithdrawRialController@confirm')->name('admin.withdraw-rial.confirm');
    Route::resource('withdraw-rial', 'WithdrawRialController', ['as' => 'admin']);


    // مدیریت کارمزد ها
    Route::get('manage/fees', "AdminController@fees_index")->name('admin.manage.fees.index');
    Route::post('manage/fees', "AdminController@fees_store")->name('admin.manage.fees.store');


    //    TRADE MANAGE
//    Route::get('trade-management', 'AdminController@manage_trade_page')->name('trade-management');
//    Route::post('trade-fee-update', 'AdminController@trad_fee_update')->name('trad-fee-update');
//    Route::post('trade-fees-update', 'AdminController@trad_fees_update')->name('trad-fees-update'); // اینو خانم سواری گفت post کنم
    Route::get('get-currency-fees', 'AdminController@get_currency_fees')->name('get-currency-fees');
    Route::get('set-fees', 'AdminController@set_fees')->name('set-fees');

    Route::get('users', 'UserController@index')->name('user.index');
    Route::get('users/authenticate/{user}', 'UserController@form_authenticate')->name('user.authenticate.form');
    Route::get('users/authenticate', 'UserController@authenticate')->name('user.authenticate.index');
    Route::get('users/{user}', 'UserController@show')->name('user.show');
    Route::post('users/{user}/wallet', 'UserController@wallet')->name('admin.users.wallet');
    Route::post('users/{user}/reject-dirham-diposit', 'UserController@rejectDirhamDeposit')->name('admin.users.reject_dirham_diposit');
    Route::post('users/{user}/confirm-dirham-diposit', 'UserController@confirmDirhamDeposit')->name('admin.users.confirm_dirham_diposit');
    Route::get('user/changeStatus', 'UserController@change_status');
    Route::post('user/{user}/edit', 'UserController@edit')->name('admin.user.edit');
//    Route::post('user/{user}/role', 'UserController@role')->name('admin.user.manage-role');
    Route::get('user/{user}/login-panel', 'UserController@login_panel')->name('admin.user.login-panel');
    Route::get('user/disableStatus', 'UserController@disable_status');
    Route::get('tickets', 'TicketController@index')->name('ticket.admin.index');
    Route::get('ticket/create', 'TicketController@create')->name('ticket.admin.create');
    Route::post('ticket/store', 'TicketController@store')->name('ticket.admin.store');
    Route::get('my_tickets', 'TicketController@index')->name('my_ticket.admin.index');
    Route::get('ticket/{id}', 'TicketController@show')->name('ticket.admin.show');
    Route::get('ticket/ban/{id}', 'TicketController@ban')->name('ticket.admin.ban');
    Route::get('get-users', 'TicketController@users')->name('admin.users');
    Route::delete('ticket/destroy/{id}', 'TicketController@destroy')->name('ticket.destroy');
    Route::post('ticket/route/{id}', 'TicketController@route')->name('ticket.route');
    Route::post('comment/{id}', 'TicketController@comment')->name('comment.admin.store');
    Route::resource('currencies', 'CurrencyController');
    Route::get('roles', "RolesController@index")->name('roles.index');
    Route::get('roles/create', "RolesController@create")->name('roles.create');
    Route::post('roles/store', "RolesController@store")->name('roles.store');
    Route::get('roles/{id}/edit', "RolesController@edit")->name('roles.edit');
    Route::post('roles/{id}/update', "RolesController@update")->name('roles.update');
    Route::delete('roles/delete', "RolesController@destroy")->name('roles.destroy');
    Route::get('banks', 'BankController@index')->name('admin.bank.index');
    Route::post('banks/{bank}/confirm', 'BankController@confirm')->name('admin.bank.confirm');
    Route::post('banks/{bank}/reject', 'BankController@reject')->name('admin.bank.reject');
    Route::resource('notifications', 'NotificationController');
    Route::get('get-user', 'NotificationController@users')->name('notifications.get_user');
    Route::get('reports', 'ReportController@index')->name('admin.report.index');
    Route::resource('posts', 'PostController');
    Route::post('posts/reject', 'PostController@reject')->name('posts.reject');
    Route::post('posts/accept', 'PostController@accept')->name('posts.accept');
    Route::resource('categories', 'CategoryController');
    Route::post('categories/delete', 'CategoryController@delete')->name('categories.delete');
//    Route::post('manage-fee-withdraw-admin-update', 'AdminController@fee_withdraw_admin_update')->name('manage-fee-withdraw-admin-update');
    Route::get('request/withdraw', 'WDController@index_withdraw')->name('admin.request.withdraw');
    Route::get('request/withdraw/{id}/show', 'WDController@show_withdraw')->name('admin.request.withdraw.show');
    Route::post('request/withdraw/balance/admin', 'WDController@balance_admin')->name('admin.request.withdraw.balance-admin');
    Route::post('request/withdraw/update-status', 'WDController@update_status')->name('admin.request.withdraw.update-status');

    Route::resource('announcements','AnnouncementController')->names('admin.ann');
});

routes/web.php
    Route::get('/price-detail/{currency}', 'HomeController@price_detail')->name('landing.price_detail');
    Route::get('/chart', 'HomeController@chart')->name('landing.chart');
    Route::get('/post/{slug}', 'HomeController@post_show')->name('landing.post');
    Route::get('/search', 'HomeController@post_search')->name('landing.search');
    Route::get('/contact-rootix', 'HomeController@contact_us')->name('landing.contact_us');

});

Route::get('withdraw/token/{token}', "App\Http\Controllers\User\WithdrawController@verifyEmail")->name('verify-withdraw.email');
Route::get('reject/token/{token}', "App\Http\Controllers\User\WithdrawController@rejectEmail")->name('reject-withdraw.email');


///// Route User
Route::middleware(['auth', 'steps', '2fa'])->namespace("App\Http\Controllers\User")->group(function () {
    ///// Route Step
    Route::prefix('step')->group(function () {
        Route::get('verify-mobile', "StepsController@mobile")->name('step.verify-mobile');
        Route::get('verify-email', "StepsController@email")->name('step.verify-email');
        Route::post('verify-mobile/send-verify', "StepsController@sendVerify")->name('step.send-verify');
        Route::post('verify-email/send-link', "StepsController@sendEmail")->name('step.send-email');
        Route::get('information', "StepsController@information")->name('step.information');
        Route::post('information/store', "StepsController@informationStore")->name('step.information.store');
        Route::get('bank', "StepsController@bank")->name('step.bank');
        Route::post('bank/store', "StepsController@bankStore")->name('step.bank.store');
        Route::get('upload_document', "StepsController@docs")->name('step.upload');
        Route::post('upload_document/store', "StepsController@DocsStore")->name('step.upload.store');
        Route::get('finish', "StepsController@finish")->name('step.finish');
    });

    Route::post('google2fa/authenticate', function () {
        return redirect(\route('user.dashboard'));
    });
    Route::get('dashboard', "HomeController@dashboard")->name('user.dashboard');
    Route::post('timer_deposit', "HomeController@timer_deposit")->name('user.timer_deposit');
    Route::get('profile', "ProfileController@formProfile")->name('user.profile.form');
    Route::post('profile/about/{id}', "ProfileController@update")->name('profile.update.about');
//    Route::get('swap/{unit}', 'SwapController@show')->name('swap.show');


    Route::get('swap', 'SwapController@index')->name('swap.index');
    Route::post('swap', 'SwapController@store')->name('swap.store');


    Route::post('get-list-currencies', 'AssetController@list_currencies')->name('asset.get_list_currencies');
//    Route::post('get-unit-price', 'SwapController@get_unit_price')->name('get-unit-price');
//    Route::post('get-unit-swap-fee-price', 'SwapController@get_unit_swap_fee_price')->name('get-unit-swap-fee-price');
    Route::post('get_theter_price', 'HomeController@get_theter_price')->name('get_theter_price');
//    Route::post('exchange', 'SwapController@exchange')->name('exchange');
    Route::post('createAccount/{unit}', 'ProfileController@wallet')->name('createAccount');
//    Route::post('check-withdraw-amount', 'WithdrawController@check_withdraw_amount')->name('check-withdraw-amount');
//    Route::post('withdraw-from-wallet', 'WithdrawController@withdraw_from_wallet')->name('withdraw-from-wallet');
//    Route::post('send-message-admin', 'WithdrawController@send_message_admin')->name('send-message-admin');
    Route::post('get-total-usdt', 'WithdrawController@get_total_usdt')->name('get-total-usdt');
//    Route::get('withdraw/{unit}','WithdrawController@index')->name('withdraw.index');
//    Route::post('withdraw','WithdrawController@store')->name('withdraw.store');
    Route::get('withdraw/token/{token}', "WithdrawController@verifyEmail")->name('verify-withdraw.email');

//    Route::resource('withdraw-rial','WithdrawRialController');
    Route::get('wallet/deposit/dirham', 'WDController@dirhamDepositIndex')->name('wallet.deposit.dirham.index');
    Route::get('wallet/withdraw/rial', 'WDController@W_withdraw_index_rial')->name('wallet.withdraw.rial.index');
    Route::get('wallet/withdraw/rial/create', 'WDController@W_withdraw_create_rial')->name('wallet.withdraw.rial.create');
    Route::post('wallet/withdraw/rial', 'WDController@W_withdraw_store_rial')->name('wallet.withdraw.rial.store');

//    Route::get('wallet/deposit/rial/create', 'WDController@W_deposit_create_rial')->name('wallet.deposit.rial.create');
//    Route::post('wallet/deposit/rial', 'WDController@W_deposit_store_rial')->name('wallet.deposit.rial.store');
    Route::get('wallet/deposit/aed/create', 'WDController@W_deposit_create_aed')->name('wallet.deposit.aed.create');
    Route::post('wallet/deposit/aed', 'WDController@W_deposit_store_aed')->name('wallet.deposit.aed.store');

    Route::get('reject/token/{token}', "WithdrawController@rejectEmail")->name('reject-withdraw.email');
    Route::get('change-pass', 'ProfileController@change_pass_view')->name('change_pass.index');
    Route::post('change-pass', 'ProfileController@change_pass')->name('change_pass.store');
    Route::get('/charge-wallet', '\App\Http\Controllers\General\PaymentController@chargeWallet')->name('charge_wallet.view');
    Route::resource('tickets', 'TicketController');
    Route::post('comment/{id}', 'TicketController@comment')->name('comment.store');
    Route::post('/setting/change_confirmation_type', 'SettingController@change_confirmation_type')->name('setting.change_confirmation_type');
    Route::post('/setting/verify_confirmation_type', 'SettingController@verify_confirmation_type')->name('setting.verify_confirmation_type');
    Route::get('setting', 'SettingController@form')->name('setting.form');
    Route::post('/setting/status-google-authenticator', 'SettingController@status_google_authenticator')->name('setting.status_google_authenticator');
    Route::post('/setting/login_2fa', 'SettingController@login_2fa')->name('setting.login_2fa');

    Route::get('/sell-currency', 'SellBuyController@sellCurrencyView')->name('sell_currency.view');
    Route::post('get-user-assets', 'AssetController@get_user_assets');
    Route::resource('wallet', 'AssetController');
    Route::post('wallet/refresh', 'AssetController@refresh_wallet')->name('wallet.refresh');
    Route::resource('banks', 'BankController')->middleware("can:user-check,bank");
    Route::post('update-profile-picture/{user}', 'ProfileController@update_avatar')->name('profile.update.picture');
    Route::post('/complete-registration', 'ProfileController@completeRegistration')->name('complete-registration');
    Route::post('get-address-wallet', 'WDController@getAddressWallet')->name('wallet.get-address-wallet');
    Route::post('withdrawal-fee', 'WDController@WithdrawalFee')->name('wallet.withdrawal-fee');
    Route::post('withdraw', 'WDController@withdraw')->name('withdraw.store')->middleware(['auth', '2fa']);
    Route::get('withdraw/index','WDController@index')->name('withdraw.index');
    Route::get('wallet/deposit/{unit}', 'WDController@deposit_form')->name('deposit-form');
    Route::get('wallet/withdraw/{unit}', 'WDController@withdraw_form')->name('withdraw-form');
    Route::post('security-withdraw', 'WDController@security_withdraw')->name('withdraw.security');
    Route::post('security-send-sms', 'WDController@security_send_sms')->name('withdraw.send-sms');
    Route::get('transactions', 'TransactionController@index')->name('transactions.index');
    //Route::resource('notification', 'NotificationController')->names('notification');
    Route::delete('/notifications/clear_all', 'NotificationController@clear_all')->name('notifications.clear_all');
    Route::get('exchange/{des_unit}-{source_unit}', 'ExchangeController@index')->name('exchange.index');
    Route::post('exchange/new-trade', 'ExchangeController@new_trade')->name('exchange.new-trade');
    Route::get('exchange/cancel-trade/{id}', 'ExchangeController@cancel_trade')->name('exchange.cancel-trade');
    Route::post('exchange/list-request','ExchangeController@list_request')->name('exchange.list-request');
    Route::post('exchange/last-transaction','ExchangeController@last_transaction')->name('exchange.list-transaction');
    Route::post('exchange/markets','ExchangeController@markets')->name('exchange.list-markets');

    Route::get('/logged-in-devices', 'LoggedInDeviceManager@index')->name('logged-in-devices.list');

    Route::get('/logout/all', 'LoggedInDeviceManager@logoutAllDevices')->name('logged-in-devices.logoutAll');

    Route::get('/logout/{device_id}', 'LoggedInDeviceManager@logoutDevice')->name('logged-in-devices.logoutSpecific');

//    Route::delete('/clear-notif', 'HomeController@clear_notif')->name('clear_notif');
    Route::post('/visit-ann','AnnouncementController@visit')->name('ann.visit');

    Route::get('dashboard/max-currencies','HomeController@max_currencies')->name('dashboard.max-currencies');
});


Route::match(['post', 'get'], 'payment/verify', "App\Http\Controllers\General\PaymentController@paymentSuccess")->name('payment.success');
Route::get('payment/{type}', "App\Http\Controllers\General\PaymentController@paymentShow")->name('payment.show');
Route::get('force-logout/{token}', 'App\Http\Controllers\Auth\LoginRegisterController@force_logout')->name('force-logout');

///// Route General
Route::middleware('auth')->namespace("App\Http\Controllers\General")->group(function () {
    Route::post('payment', "PaymentController@payment")->name('payment');
});
Route::match(['post', 'get'], 'payment/verify', "App\Http\Controllers\General\PaymentController@paymentSuccess")->name('payment.success');
Route::get('payment/{type}', "App\Http\Controllers\General\PaymentController@paymentShow")->name('payment.show');
Route::get('force-logout/{token}', 'App\Http\Controllers\Auth\LoginRegisterController@force_logout')->name('force-logout');

app/Models/Notification.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Notification extends Model
{
    use HasFactory;

    protected $fillable=[
        'refer_id',
        'user_id',
        'type',
        'is_viewed',
        'details',
    ];

    protected $casts = [
        'details' => 'array',
    ];

    public function user_guard(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(UserGuard::class,'user_id');
    }

    public function notification_view(): \Illuminate\Database\Eloquent\Relations\HasOne
    {
        return $this->hasOne(NotificationView::class,'notification_id');
    }
}

app/Models/NotificationView.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class NotificationView extends Model
{
    use HasFactory;
    protected $fillable=[
        'notification_id',
        'user_id'
    ];
}

resources/views/admin/notifications/create.blade.php
@extends('templates.admin.master_page')
@section('title_browser')
    ایجاد پیغام
@endsection
@section('style')
    <style>
        button {
            overflow: hidden !important;
        }
        #ckeditor{
            display: none;
        }
    </style>
@endsection
@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form action="{{route('notifications.store')}}" method="post">
                        @csrf
                        <div class="row justify-content-center">
                            <div class="form-group col-lg-10 col-md-4 col-sm-6">
                                <label for="example-text-input" class="">عنوان</label>
                                <input type="text" name="title" class="form-control">
                            </div>
                        </div>
                        <div class="row justify-content-center">
                            <div class="form-group col-lg-10 col-md-4 col-sm-6">
                                <label for="example-text-input" class="">توضیحات</label>
                                <textarea id="ckeditor" name="description" rows="10" cols="125">
            </textarea>
                            </div>
                        </div>
                        <div class="row justify-content-center">
                            <div class="form-group col-lg-2 col-md-3 col-sm-6 mt-3">
                                <div class="form-check">
                                    <input class="receiver" type="radio" name="receiver" id="exampleRadios1" value="0" checked>
                                    <label class="form-check-label" for="exampleRadios1">
                                        همه کاربران
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="receiver" type="radio" name="receiver" id="exampleRadios2" value="1">
                                    <label class="form-check-label" for="exampleRadios2">
                                        کاربر خاص
                                    </label>
                                </div>

                            </div>
                            <div class="form-group col-lg-3 col-md-4 col-sm-6 d-none">
                                <label for="example-text-input" class="">کاربران</label>
                                <select id="users" type="text" name="user_id" class="form-control users">
                                    <option value="">انتخاب کنید...</option>
                                </select>
                            </div>
                            <div class="form-group col-lg-2 col-md-4 col-sm-6">
                                <label for="example-text-input">رنگ پیغام</label>
                                <select name="color" class="form-control">
                                    <option value="info">info</option>
                                    <option value="warning">warning</option>
                                    <option value="danger">danger</option>
                                </select>
                            </div>
                            <div class="form-group col-lg-4 col-md-4 col-sm-6">
                                <label for="example-text-input" readonly>تاریخ</label>
                                <sub class="text-danger">درصورت تمایل به ارسال در زمان حاضر این فیلد را پر نکنید.</sub>
                                <input name="started_at" class="form-control datepicker" readonly>
                            </div>
                            <div class="form-group col-lg-1 col-md-4 col-sm-6">
                                <label for="example-text-input">آیکون</label>
                                <span class="input-group-prepend">
            <button name="icon" class="btn btn-danger" data-icon="" role="iconpicker"></button>
        </span>

                            </div>
                        </div>
                        <div class="row justify-content-center">
                            <button type="submit" class="btn btn-info btn-lg ajaxStore">ایجاد پیغام</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $(document).ready(function () {
            $(document).on('change','.receiver',function (){
                var val=$(this).val();
                var elem=$(".users").closest(".form-group");
                if (val==1) {
                    elem.removeClass('d-none');
                }else {
                    elem.addClass('d-none');
                }
            })
            $('.users').select2({
                width: '100%',
                minimumInputLength: 3,
                ajax: {
                    url: `{{ route('notifications.get_user') }}`,
                    dataType: 'json',
                    type: "get",
                    processResults: function (data) {
                        return {
                            results: $.map(data, function (item) {
                                return {
                                    text: item.email,
                                    id: item.id,
                                }
                            })
                        };
                    }
                }
            });
        });

        CKEDITOR.replace('ckeditor',
            {
                customConfig: 'config.js',
                toolbar: 'simple'
            });
    </script>
@endsection

resources/views/admin/notifications/index.blade.php
@extends('templates.admin.master_page')
@section('title_browser')
    پیغام ها
@endsection
@section('content')
    <div class="row m-2 justify-content-end">
        <div class="col-4 text-left">
                        <a href="{{route('notifications.create')}}" class="btn btn-success btn-lg text-white">ایجاد پیغام</a>
                    <!-- end col -->
            <!-- end page-title-box -->
        </div>
    </div>
    <!-- end page title -->
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive text-center">
                        <table class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <td>عنوان</td>
                                <td>متن</td>
                                <td>نوع پیغام</td>
                                <td>تاریخ</td>
                                <td>وضعیت پیغام</td>
                                <td>عملیات</td>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($notifications as $item)
                                @php
                                    $notif_type=null;
                                    $notif_status=null;
                                        if(\Carbon\Carbon::parse($item->started_at)->isPast())
                                             $notif_status='ارسال شده';
                                        else
                                             $notif_status='در انتظار ارسال';

                                            switch ($item->color){
                                                    case 'info':
                                                        $notif_type='عادی';
                                                    break;
                                                    case 'warning':
                                                        $notif_type='هشدار';
                                                    break;
                                                    case 'danger':
                                                        $notif_type='اخطار';
                                                    break;
                                            }
                                @endphp
                                <tr>
                                    <td>{{$item->title}}</td>
                                    <td>{!! \Illuminate\Support\Str::limit($item->description,30) !!}</td>
                                    <td><span class="btn btn-sm btn-{{$item->color}} p-1">{{$notif_type}}</span></td>
                                    <td>{{\Carbon\Carbon::parse($item->started_at)->format('Y-m-d')}}</td>
                                    <td>{{$notif_status}}</td>
                                    @if(\Carbon\Carbon::parse($item->started_at)->isPast())
                                        <td>-</td>
                                    @else
                                        <td><a href="{{route('notifications.edit',$item->id)}}" class="btn btn-sm btn-success"><i class="fa fa-edit"></i></a></td>
                                    @endif
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        {!! $notifications->links() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection